name: Deploy to DigitalOcean

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: webfactory/ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DO_SSH_PRIVATE_KEY }}

      - name: Deploy to Droplet
        run: |
          ssh -o -p 44444 StrictHostKeyChecking=no derrick@134.199.153.51 "/derrick/app/digital-ocean-github-actions-ci/scripts/deploy.sh"
